[package]
name = "eruption"
version = "0.1.11"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2018"
description = "Linux user-mode driver for the ROCCAT Vulcan 100/12x series keyboards"
repository = "https://gitlab.com/X3n0m0rph59/eruption-roccat-vulcan.git"
homepage = "https://x3n0m0rph59.gitlab.io/eruption-roccat-vulcan/"
license = "GPLv3+"
readme = "README.md"

[dependencies]
parking_lot = { version = "0.11.0", features = ["deadlock_detection"] }
tokio = { version = "1.18.5", features = ["full"] }
tracing = "0.1.17"
tracing-futures = "0.2.4"
tracing-subscriber = "0.2.9"
libc = "0.2.73"
nix = "0.17.0"
prctl = "1.0.0"
log = "0.4.11"
pretty_env_logger = "0.4.0"
failure = "0.1.8"
toml = "0.5.6"
serde = { version = "1.0.114", features = ["derive"] }
ctrlc = { version = "3.1.5", features = ["termination"] }
clap = "2.33.1"
hotwatch = "0.4.3"
config = "0.10.1"
hidapi = { git = "https://github.com/ruabmbua/hidapi-rs.git", branch = "master" }
udev = "0.4.0"
evdev-rs = "0.4.0"
hexdump = "0.1.0"
bytevec = "0.2.0"
byteorder = "1.3.4"
itertools = "0.9.0"
rayon = "1.3.1"
lazy_static = "1.4.0"
rand = "0.7.3"
palette = "0.5.0"
nalgebra = "0.21.1"
noise = "0.6.0"
simdnoise = "3.1.6"
interpolation = "0.2.0"
rlua = "0.17.0"
sysinfo = "0.15"
systemstat = "0.1.5"
procinfo = "0.4.2"
rustfft = "3.0.1"
hound = "3.4.0"
libpulse-binding = "2.16"
libpulse-simple-binding = "2.16"
uuid = { version = "0.8.1", features = ["serde", "v4"] }
dbus = "0.8.4"
paste = "0.1"
procmon-sys = { version = "0.0.2", path = 'src/procmon-sys' }

# ubuntu bionic
# sysinfo = "=0.14.2"
# libpulse-binding = { git = "https://github.com/jnqnfe/pulse-binding-rust.git", branch = "travis-bionic-1" }
# libpulse-simple-binding = { git = "https://github.com/jnqnfe/pulse-binding-rust.git", branch = "travis-bionic-1" }

[dev-dependencies]
tokio = { version = "1.18", features = ["test-util"] }

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 8
panic = 'unwind'

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'unwind'
