[package]
name = "eruption"
version = "0.0.8"
authors = ["X3n0m0rph59 <x3n0m0rph59@gmail.com>"]
edition = "2018"
description = "Linux user-mode driver for the ROCCAT Vulcan 100/12x series keyboards"
repository = "https://gitlab.com/X3n0m0rph59/eruption-roccat-vulcan.git"
homepage = "https://x3n0m0rph59.gitlab.io/eruption-roccat-vulcan/"
license = "GPLv3+"
readme = "README.md"

[features]
default = ["all"] #["dbus"]
all = ["frontend", "dbus"]
frontend = ["rocket", "rocket_contrib"]

[dependencies]
libc = "0.2.60"
nix = "0.14.1"
prctl = "1.0.0"
log = "0.4.8"
pretty_env_logger = "0.3.0"
failure = "0.1.5"
toml = "0.5.1"
serde = { version = "1.0.98", features = ["derive"] }
ctrlc = { version = "3.1.3", features=["termination"] }
clap = "2.33.0"
config = "0.9.3"
hidapi = { git = "https://github.com/X3n0m0rph59/hidapi-rs.git", branch = "master" }
udev = "0.2.0"
evdev-rs = "0.2.0"
hexdump = "0.1.0"
#itertools = "0.8.0"
#rayon = "1.0"
lazy_static = "1.3.0"
rand = "0.7.0"
rlua = "0.16.3"
sysinfo = "0.9.1"
systemstat = "0.1.4"
procinfo = "0.4.2"
dbus = { version = "0.6.5", optional = true }
rocket = { version = "0.4.2", optional = true }
rocket_contrib = { version = "0.4.2", optional = true, features = ["tera_templates"] }

[profile.dev]
opt-level = 0
debug = true
rpath = false
lto = false
debug-assertions = true
codegen-units = 8
panic = 'unwind'

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'unwind'
